version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(java)"
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(python)"
    groups:
      python-deps:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(terraform)"