version: 2
updates:
# -------------------------------------------------------------------
# Java / Gradle
# -------------------------------------------------------------------
  - package-ecosystem: "gradle"
    directory: "/java"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(java)"
      include: "scope"
    open-pull-requests-limit: 4
    labels:
      - "deps"
      - "lang:java"
# Matching rules
    allow:
      - dependency-type: "direct"
      - dependency-name: "org.springframework.boot:*"
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"
    ignore:
      - dependency-name: "com.google.guava:guava"
        update-types: ["minor"]
      - dependency-name: "org.apache.commons:commons-lang3"
        update-types: ["major"]
# Grouping rules
    groups:
# One PR for all security-related updates
      security-fixes:
        applies-to: security-updates
        patterns:
          - "*"
# One PR for safe version bumps
      regular-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types: ["minor", "patch"]
# Isolate major upgrades
      major-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types: ["major"]
# -------------------------------------------------------------------
# Python / pip
# -------------------------------------------------------------------
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(python)"
    open-pull-requests-limit: 2
    labels:
      - "deps"
      - "lang:python"
    groups:
      python-core:
        patterns:
          - "^django$"
          - "^requests$"
      python-others:
        patterns:
          - "*"
        exclude-patterns:
          - "^django$"
          - "^requests$"
    ignore:
      - dependency-name: "numpy"
        update-types: ["major"]
# -------------------------------------------------------------------
# Terraform
# -------------------------------------------------------------------
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(terraform)"
    labels:
      - "deps"
      - "infra"
    groups:
      terraform-providers:
        patterns:
          - "^hashicorp/.*"
      terraform-modules:
        patterns:
          - ".*module.*"
# -------------------------------------------------------------------
# GitHub Actions
# -------------------------------------------------------------------
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions)"
    labels:
      - "deps"
      - "ci"
# -------------------------------------------------------------------
# Docker
# -------------------------------------------------------------------
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(docker)"
    labels:
      - "deps"
      - "containers"
